### ISSUE TITLE
Support non-self-define custom-elements

### ISSUE THREAD

**Issue by georges-gomes** [webcomponents/custom-elements-manifest#11]
# Why?

I know this is controversial, but I'm not entirely confortable about *only* self-define custom-element.
There is so much opportunity for tag collision...

I know there are other issues if we don't use self-define components but it will ultimately be resolved by [Scoped Registries](https://github.com/w3c/webcomponents/issues/716). 

Additionally, I can see a number of use cases where it would make sense to control programmatically the tag name and the discovery of the class in a module. I would definitely need it in my project for example.

# Cases

If `custom-elements.json` has a `tagName` then it was self define by the module.
If `custom-elements.json` has no `tagName` you need to define.
- option 1: The module expose the class as a named `export`. 
- option 2: The module expose the class as `export default`.

# Proposal 

`exportName = default | xxxxxxx` in the schema
(xxxxxxx being the exported name of the class)

**Comment by KrisGraySFDC** [comment]
Not totally following you on the need for defining metadata for a component without a tag name. 
 
You seem to be implying that in combination to the custom-elements.json file, consumers would also need to parse the module file to get all the metadata on a component which seems like what we're trying to avoid.

**Comment by georges-gomes** [comment]
@KrisGraySFDC No need to "parse the module", it would just be nice to have `custom-elements.json`  with `exportName` of the custom element `class` in the module.
So the host can define it as he wants.

**Comment by KrisGraySFDC** [comment]
Gotcha. I can imagine why you might want something like this, but can you provide a concrete use case?

**Comment by georges-gomes** [comment]
First, Tag name could collide.

And I think there are many think we can do by loading the class and define it manually.
Enhancing the class, applying global behavior, etc... It opens lots of possibilities in a standard way.
We do some of this on webcomponents.dev and it has been very useful and clean.

**Comment by KrisGraySFDC** [comment]
Can you point us to some sample code?

**Comment by justinfagnani** [comment]
#18 is a start at addressing this

**Comment by justinfagnani** [comment]
We support this with separate custom element declarations (the class) and exports (the define call).
