### ISSUE TITLE
Access modifier issue on derived class

### ISSUE THREAD

**Issue by DavideMininni-Fincons** [webcomponents/custom-elements-manifest#131]
Hello guys :)
I was doing some refactoring on the Lit project I'm working on, and I found a little issue.

Let's say I have a base class `B` with an abstract public method `open`, and a derived class `D` that implement it. 
Then I create a second derived class `D2`, and I want the method in `D2` to not be public;
so I change the base method in `B` from public to protected.
This way, I would expect that `D` would expose a public `open`, while in `D2` I would leave it as protected.

However, the public modifier from `D` is not taken into account when the manifest is created and the method is always marked as protected. I created a little demo here:
https://github.com/DavideMininni-Fincons/custom-element-manifest-demo/tree/main

**Comment by thepassle** [comment]
This repository is for defining what the custom-elements.json schema looks like. The issue you're running into is with `@custom-elements-manifest/analyzer`, which is a tool that implements and outputs the schema. Please create an issue on the repository of `@custom-elements-manifest/analyzer` instead
