### ISSUE TITLE
add reflect to property or attribute

### ISSUE THREAD

**Issue by bennypowers** [webcomponents/custom-elements-manifest#36]
There should be a way to signal whether or not a property reflects to it's associated attribute when set

**Comment by justinfagnani** [comment]
I think to do this the way we've done other features where a custom element adds interface on top of classes we should introduce a CustomElementField that extends a ClassField:

```ts
interface CustomElementClassField extends ClassField {
 attribute?: string;
 reflects?: boolean;
}
```

Then change CustomElement to override `members`:

```ts
  members?: Array<CustomElementMember>;
```
