### ISSUE TITLE
Spread parameters

### ISSUE THREAD

**Issue by bennypowers** [webcomponents/custom-elements-manifest#61]
As far as I could tell there's no schema to identify a spread parameter:

https://github.com/webcomponents/custom-elements-manifest/blob/e527701c69ebebff1cfb85299bf54d839def0061/schema.d.ts#L542-L547

https://github.com/webcomponents/custom-elements-manifest/blob/e527701c69ebebff1cfb85299bf54d839def0061/schema.d.ts#L442-L458

This could be useful for class methods or functions that take a spread:
```ts
  protected notify(...keys: (keyof this)[]): void {
    this[update](Object.fromEntries(keys.map(x => [x, this[x]])));
  }
```

**Comment by thepassle** [comment]
For all intents and purposes this would just be:

```json
"parameters": [
  {
    "name": "keys",
    "type": {
      "text": "(keyof this)[]"
    }
  }
]
```

Right?

**Comment by bennypowers** [comment]
```js
this.notify(['a','b','c']);
this.notify(...['a','b','c']);
this.notify('a','b','c');
```

**Comment by thepassle** [comment]
But these would all be internally handled as being an array, right? No matter how the method is _called_, the method expects the argument to be an array. Im not sure what value we could add here

**Comment by bennypowers** [comment]
it's an array in the function body, but a spread at the call site

so, if the user followed the documentation as you defined it, they would

```js
this.notify(['a','b','c']);
```
but that would break because `keys.map(x => [x, this[x]]` would evaluate to 
```js
[[
  ['a','b','c'],
  /* not something you can index this with*/
  this[['a','b','c']
]]
```
instead of the intended:
```js
[
  ['a', this.a],
  ['b', this.b],
  ['c', this.c]
]
```

**Comment by thepassle** [comment]
> `this.notify(['a','b','c']);`

Thats a fair point. How would this look like in the schema, though?

**Comment by bennypowers** [comment]
off the top
```js
notify(a, ...keys, b) {}
```
```json
"parameters": [
  { "name": "a" },
  {
    "name": "keys",
    "rest": true
  }, 
  { "name": "b" }
]
```

**Comment by bennypowers** [comment]
yeah, 🚲

**Comment by bennypowers** [comment]
i'd usually reach for an enum rather than a spread, maybe
```json
"kind": "rest"
```
```ts
declare module 'schema' {
  export type Parameter {
    kind?: "rest"|"spread"
  }
}
```

**Comment by justinfagnani** [comment]
We should do this, but I think a simple boolean like `rest?: true` would probably suffice. There's no other value on the single vs rest axis to represent. `spread` isn't a kind of parameter, it's an operation you can use for arguments, but we don't document calls/arguments. `rest?: true` goes alone with `optional?: true` that we have now.
