### ISSUE TITLE
look for similarities with web-types

### ISSUE THREAD

**Issue by jogibear9988** [webcomponents/custom-elements-manifest#65]
see https://github.com/JetBrains/web-types
and the comment here:  https://github.com/WICG/webcomponents/issues/776#issuecomment-762109185

**Comment by justinfagnani** [comment]
I looked at the web-type schema and it doesn't seem sufficient for our use cases. It doesn't seem to describe the JavaScript interface of components much if at all, and seems like it has a lot of Vue-specific concepts in it.
