### ISSUE TITLE
Using export map instead of custom property in `package.json`

### ISSUE THREAD

**Issue by daKmoR** [webcomponents/custom-elements-manifest#67]
currently, it says

> ## Referencing manifests from npm packages
> 
> In order to allow tools to find npm packages with custom element manifests without having to download package tarballs, > packages should have a `"customElements"` field in their `package.json` that points to the manifest:
> ```json
> {
>   "name": "example-package",
>   "customElements": "custom-elements.json",
> }
> ```

but if you are using an export map
```js
"name": "my-package",
"customElements": "custom-elements.json",
"exports": {
  ".": "./index.js"
}
```

then the files can not be imported... e.g. this will fail
```js
import cem from 'my-package/custom-elements.json' assert { type: 'json' };
```

## Suggestion

Replace the custom property with an entry in the export map.

Benefits:
- resolving is depending on an import map or the node resolution system
- file is always accessible as it's part of the export map
- not 2 different ways of defining an `CEM`

```diff
- "customElements": "custom-elements.json",
+ "exports": {
+  "customElements": "custom-elements.json",
+  ".": "./index.js"
+ }
```

**Comment by thepassle** [comment]
For the foreseeable future, not all packages will make use of export maps yet, so I think we'll have to have two ways for now:

If a package uses export maps:
```json
 "exports": {
   "customElements": "custom-elements.json",
 }
```

If a package does not use export maps yet, add a field in the `package.json`:
```json
"customElements": "custom-elements.json"
```

**Comment by justinfagnani** [comment]
As discussed in our meeting about this, a manifest could be included in package exports if the package intends it to be an _importable_ JSON module from a consuming package, but this isn't a primary use case.

The use case we most need to cover is for a source analyzing tool to be able to discover a package.json and custom elements manifest given a base path and a specifier, resolving the specifier within the source's available node_modules tree, not the tool's. This may require implementing part of Node's module resolution algorithm as a utility function. We'll need this whether or not the custom elements manifest is exported.

I think we can close this as an issue that's part of the manifest spec and figure it out in tools.
