### ISSUE TITLE
Support for Inheritence/Mixin state

### ISSUE THREAD

**Issue by daKmoR** [webcomponents/custom-elements-manifest#7]
Consider the following code:

```js
class DisabledElement extends LitElement {}
class MyInput extends FieldMixin(DisabledElement) {}
```

how would we save this nicely to the json?

strawman proposal:

```json
{
  "tags": [
    {
      "name": "my-input",
      "inheritance": "FieldMixin -> DisabledElement -> LitElement",
      "properties": [
        {
          "name": "myInputState",
          "inheritance": "this"
        },
        {
          "name": "value",
          "inheritance": "FieldMixin"
        },
        {
          "name": "disable",
          "inheritance": "DisabledElement"
        }
      ]
    }
  ]
}
```

as this is probably not that simple to analyze? I thought we could postpone it? but yeah if anyone things that's easily doable by an analyzer and it totally make sense like this we could move forward with it?

**Comment by justinfagnani** [comment]
This is very doable. We have [superclass](https://github.com/Polymer/tools/blob/master/packages/analyzer/src/analysis-format/analysis-format.ts#L178) and [mixins](https://github.com/Polymer/tools/blob/master/packages/analyzer/src/analysis-format/analysis-format.ts#L162) in the Polymer analysis schema.

Though they really should be some kind of compound reference type, not just a string. Ie:

```ts
interface Reference {
  moduleName: string;
  exportedName: string;
}

interface Class extends Feature {
  superclass: Reference;
  mixins?: Array<Reference>;
}
```

**Comment by daKmoR** [comment]
genuine question - how to bring that into json?

**Comment by justinfagnani** [comment]
Oh, that's just a bit of TypeScript because it's much easier for me to read than JSON schema. You can compile TypeScript interfaces to JSON schema with https://github.com/YousefED/typescript-json-schema

**Comment by daKmoR** [comment]
I'm more interested in how would a user define them in his `custom-elements.json`?

I'm not sure what the difference between `moduleName` and `exportedName` should be?

maybe something like this? 
```
{
  "tags": [
    {
      "name": "my-input",
      "inheritance": "FieldMixin -> DisabledElement -> LitElement",
      "superclass": {
        "moduleName": "DisabledElement.js",
        "exportedName": "DisabledElement"
      },
      "mixins": [
        {
          "moduleName": "FieldMixin.js",
          "exportedName": "FieldMixin"
        }
      ],
      "properties": [
        {
          "name": "myInputState",
          "moduleName": "this"
        },
        {
          "name": "value",
          "moduleName": "FieldMixin"
        },
        {
          "name": "disable",
          "moduleName": "DisabledElement"
        }
      ]
    }
  ]
}
```

**Comment by justinfagnani** [comment]
That's close I think

`modeulName` would be the import to use to get to the symbol, `exportName` would be the export of that module to use.

I'm of the opinion that the JS side of things should go into a more JS-centric section of the doc though, so I'd probably structure it something like this:

```
{
  "elements": [
    {
      "name": "my-input",
      "class": {
        "moduleName": "./MyInputElement.js",
        "exportedName": "MyInputElement"
      },
      "attributes": {
        "value": {
          "property": "value",
          "reflected": false,
        }
      }
    }
  ],
  "exports": [
    {
      "name": "MyInputElement",
      "kind": "class",
      "superclass": {
        "moduleName": "./DisabledElement.js",
        "exportedName": "DisabledElement"
      },
      "mixins": [
        {
          "moduleName": "FieldMixin.js",
          "exportedName": "FieldMixin"
        }
      ],
      "members": [
        {
          "name": "value",
          "kind": "property",
          "type": "string",
        }
      ]
    }
  ]
}
```

ie, put all the inheritance information on a class definition, and reference that from the element definition.

**Comment by daKmoR** [comment]
### Inheritence per Property
I think it's pretty important to know on a per property basis who introduced it...
As with bigger components you usually have a quite long inheritance and therefore lots and lots of properties/methods/...

so a documentation system can then for example decide
- to show only direct properties by default
- have a button to show all inherited properties

### Exports for JavaScript
What would be the use case for it? Document full javascript seems a little too much for `custom-elements.json`? if needed for a project then documentation tools for pure js or ts could be used?

### Format
I really like the simplicity of the current format - always "type" -> "array" -> "object". Really simple to convert into documentation or to process. 
```
"properties": [
  {
    "name": "myInputState",
    "moduleName": "this"
  },
  ...
]
```

Putting too much stuff into keys always seems to become rather cumbersome to work with (for me at least 🙈 - but maybe that's just me 🙈 )

side benefit would be to stay more aligned with the current vs code format

**Comment by KrisGraySFDC** [comment]
Not having the extended members in the elements json file would help here.  

By including so much in each file, we're going to be having consistency issues. 

Changes to types that are extended will require re-compilation of all of the child metadata types. Some of these you won't even control.

If we simply declare your parent as "DisabledElement" then tools could aggregate it as necessary and we wouldn't need to attach that info to each attribute.

**Comment by bennypowers** [comment]
`mixin` declarations are defined in schema.ts, but not in schema.json, is this intentional @justinfagnani

**Comment by justinfagnani** [comment]
We've supported mixins and inheritance well for a while now.
