### ISSUE TITLE
Publish latest iteration to NPM

### ISSUE THREAD

**Issue by 43081j** [webcomponents/custom-elements-manifest#87]
The version in NPM is missing a few fixes to the `CustomElementDeclaration` type (in that it is empty, just an alias of the class declaration type).

We can't directly depend on the types from this repo without that.

would be great if we can publish the latest one

**Comment by Westbrook** [comment]
@justinfagnani would you be able to help with this?

**Comment by sonntag-philipp** [comment]
@justinfagnani ping @Publish latest iteration of custom-elements-manifest to NPM

**Comment by justinfagnani** [comment]
I have a release PR up here: https://github.com/webcomponents/custom-elements-manifest/pull/110

But I think we're going to need to make it version 2.0.0 due to the changes (bug fixes) in the custom element interfaces.

cc @kevinpschaaf

**Comment by justinfagnani** [comment]
I've published version 2.0.0
