### ISSUE TITLE
I expected to see a sample custom-elements.json

### ISSUE THREAD

**Issue by steren** [webcomponents/custom-elements-manifest#90]
This repo is the first Google result for "custom-elements.json", yet nowhere is described what this file should look like in the README.

I suggest this README to show an example custom-elements.json as well as document the expected schema,. similarly to document that can be found online about package.json

**Comment by castastrophe** [comment]
Totally agree!  This is a duplicate of issues #39 and #40 so it could be closed in favor of adding suggestions there for what you would like to see included.

**Comment by justinfagnani** [comment]
Agreed. I think we could also have a folder of samples, especially to demonstrate more complete features.

Tagging @thepassle who I suspect might have the most readily available samples from his work on the CEM analyzer.

**Comment by thepassle** [comment]
I have a whole bunch of manifests here: https://github.com/open-wc/custom-elements-manifest/tree/master/packages/analyzer/fixtures

We can probably just reuse some of those.

**Comment by steren** [comment]
https://github.com/webcomponents/custom-elements-manifest/pull/91 added an example. Very useful. Thanks.
